config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'mains/show'
  resources :mains do resources :facts
                      resources :newarrivals
                      resources :abouts
                      resources :backgrounds
                      resources :galleries
  end

  resources :categories do resources :products
  end

  resources :careers
  resources :products

  root 'mains#show'
  
end

app/models/about.rb
class About < ApplicationRecord
  belongs_to :main


main = Main.find_by(id: '1')
i=0
main.abouts.each do
i=i+1
end
if i==0
about = main.abouts.create(sl: "1", data: "THE COMPLETE AQUATIC SOLUTIONS")
about.save
end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/background.rb
class Background < ApplicationRecord
  belongs_to :main
  mount_uploader :backgroundimg, BackgroundimgUploader
end

app/models/career.rb
class Career < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products, dependent: :destroy
  mount_uploader :catimg, CatimgUploader
end

app/models/fact.rb
class Fact < ApplicationRecord
  belongs_to :main
end

app/models/gallery.rb
class Gallery < ApplicationRecord
  belongs_to :main
  mount_uploader :galleryimg, GalleryimgUploader
end

app/models/main.rb
class Main < ApplicationRecord
has_many :facts, dependent: :destroy
has_many :abouts, dependent: :destroy
has_many :newarrivals, dependent: :destroy
has_many :backgrounds, dependent: :destroy
has_many :galleries, dependent: :destroy

mains = Main.all
i=0
mains.each do |check|
i=i+1
end
if i==0
main = Main.create(id: "1")
main.save
end
end

app/models/newarrival.rb
class Newarrival < ApplicationRecord
  belongs_to :main
  mount_uploader :newarrivalimg, NewarrivalimgUploader
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  mount_uploader :pdtimg, PdtimgUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/backgrounds_controller.rb
class BackgroundsController < ApplicationController
before_action :authenticate_user!

def index
	@main = Main.find_by(id: '1')
	@backgrounds = @main.backgrounds.all
end


def show
	@main = Main.find_by(id: '1')
	@background = @main.backgrounds.find(params[:id])
end

def new
	@main= Main.find_by(id: '1')
	@background = @main.backgrounds.new
end

def create
  @main = Main.find_by(id: '1')
  @background = @main.backgrounds.create(background_params)
  redirect_to main_path(@main)
end

def destroy
  @main = Main.find_by(id: '1')
  @background = @main.backgrounds.find(params[:id])
  @background.destroy
  redirect_back fallback_location: root_path
end

private
  def background_params
    params.require(:background).permit(:backgroundimg)
  end
end

app/controllers/facts_controller.rb
class FactsController < ApplicationController
before_action :authenticate_user!
def create
  @main = Main.find_by(id: '1')
  @fact = @main.facts.create(fact_params)
  redirect_to main_path(@main)
end

def destroy
  @main = Main.find_by(id: '1')
  @fact = @main.facts.find(params[:id])
  @fact.destroy
  redirect_to main_path(@main)
end

private
  def fact_params
    params.require(:fact).permit(:tip)
  end


end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/backgrounds_helper.rb
module BackgroundsHelper
end

app/helpers/careers_helper.rb
module CareersHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/facts_helper.rb
module FactsHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/mains_helper.rb
module MainsHelper
end

app/helpers/newarrivals_helper.rb
module NewarrivalsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/backgrounds/_form.html.erb
<%= form_with(model: [ @main, @main.backgrounds.build ], local: true) do |form| %>
<div class="catwrap" style="position: relative; min-height: 100vh">
	<fieldset style="margin: 4vw">
		<legend class="prodlegend" style="font-size: 4vw; margin-left: 2vw">NEW BACKGROUND IMAGE</legend>
		<div style="margin: 2vw; margin-bottom: 4vw">
			<%= form.file_field :backgroundimg, :class => "pdtnametxt" %>
		</div>

		<div>
  			<%= form.submit :SAVE, :class => "createbtn" %>
		</div>
	</fieldset>
</div>
<% end %>

app/views/backgrounds/index.html.erb
<div class="catwrap" style="position: relative">
	<fieldset>
		<legend class="prodlegend" style="font-size: 4vw; margin-left: 2vw">ALL BACKGROUND IMAGES</legend>
			<% @backgrounds.each do |background| %>			
				<div class="categoryindex">
					<div style="padding-bottom: 0.5vw; min-height: 13.1vw">
						<%= image_tag(background.backgroundimg.url, class: :productimg1) %>
					</div>
						
	          		<% if user_signed_in? and current_user.email =="justfish@gmail.com" %> 
	            		<%= link_to 'Delete', main_background_path(@main, background), method: :delete, data: { confirm: 'Are you sure?' }, :class => "dltbtn" %>
	         		<% end %>  
	   			</div>
			<% end %>
	</fieldset>
	<div style="padding: 0.3vw">
				<%= button_to 'Back to Main page', :back, :method => "get", :class => "createbtn" %>
	</div>
	<%= button_to 'HOME', root_path, :method => "get", :class => "homebtn" %>
</div>

app/views/backgrounds/new.html.erb
<%= render 'form' %>

app/views/backgrounds/show.html.erb
<div class="wrap mid" style="min-height: 100vh; position: relative">
	<div style="width: 100%; margin-top: 2.5vw; border: 1px solid gray; padding: 0; margin-bottom: 1vw; border-radius: 4px">
		<div style="display:inline-block; padding: 0.5vw 0.5vw 0.5vw 0.5vw; width:49.5%; min-height: 26vw; vertical-align: top; border-right: 1px solid black"><%= image_tag(@background.backgroundimg.url, class: :productimg2) %>
		</div>
	</div>
	<%= button_to 'BACK', :back, :method => "get", :class => "createbtn", :style => "position: absolute; bottom:0.5vw; left: 0" %>
	<%= button_to 'HOME', root_path, :method => "get", :class => "homebtn", :style => "right: 23vw" %>
    <%= button_to 'CATEGORIES', categories_path, :method => "get", :class => "catbtn", :style => "right: 0vw" %>
    <%= button_to 'PRODUCTS', products_path, :method => "get", :class => "catbtn", :style => "right: 12vw" %>
</div>