config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'mains/show'
  resources :mains do resources :facts
                      resources :newarrivals
                      resources :abouts
                      resources :backgrounds
                      resources :galleries
  end

  resources :categories do resources :products
  end

  resources :careers
  resources :products

  root 'mains#show'
  
end

app/models/about.rb
class About < ApplicationRecord
  belongs_to :main


main = Main.find_by(id: '1')
i=0
main.abouts.each do
i=i+1
end
if i==0
about = main.abouts.create(sl: "1", data: "THE COMPLETE AQUATIC SOLUTIONS")
about.save
end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/background.rb
class Background < ApplicationRecord
  belongs_to :main
  mount_uploader :backgroundimg, BackgroundimgUploader
end

app/models/career.rb
class Career < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products, dependent: :destroy
  mount_uploader :catimg, CatimgUploader
end

app/models/fact.rb
class Fact < ApplicationRecord
  belongs_to :main
end

app/models/gallery.rb
class Gallery < ApplicationRecord
  belongs_to :main
  mount_uploader :galleryimg, GalleryimgUploader
end

app/models/main.rb
class Main < ApplicationRecord
has_many :facts, dependent: :destroy
has_many :abouts, dependent: :destroy
has_many :newarrivals, dependent: :destroy
has_many :backgrounds, dependent: :destroy
has_many :galleries, dependent: :destroy

mains = Main.all
i=0
mains.each do |check|
i=i+1
end
if i==0
main = Main.create(id: "1")
main.save
end
end

app/models/newarrival.rb
class Newarrival < ApplicationRecord
  belongs_to :main
  mount_uploader :newarrivalimg, NewarrivalimgUploader
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  mount_uploader :pdtimg, PdtimgUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/facts_controller.rb
class FactsController < ApplicationController
before_action :authenticate_user!
def create
  @main = Main.find_by(id: '1')
  @fact = @main.facts.create(fact_params)
  redirect_to main_path(@main)
end

def destroy
  @main = Main.find_by(id: '1')
  @fact = @main.facts.find(params[:id])
  @fact.destroy
  redirect_to main_path(@main)
end

private
  def fact_params
    params.require(:fact).permit(:tip)
  end


end

app/controllers/mains_controller.rb
class MainsController < ApplicationController
before_action :authenticate_user!, except: [:show]

def show
  @main = Main.find_by(id: '1')
end

def edit
	@main = Main.find_by(id: '1')
end

def update
    @main = Main.find_by(id: '1')
 
    if @main.update(main_params)
      redirect_to @main
    else
      render 'edit'
    end
  end

def destroy
    @main = Main.find(params[:id])
    @main.destroy
 
    redirect_to mains_path
  end

private

	def main_params
		params.require(:main).permit(:shop, :contact_mail, :contact_no, :address)
	end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/backgrounds_helper.rb
module BackgroundsHelper
end

app/helpers/careers_helper.rb
module CareersHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/facts_helper.rb
module FactsHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/mains_helper.rb
module MainsHelper
end

app/helpers/newarrivals_helper.rb
module NewarrivalsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/facts/_form.html.erb
<%= form_with(model: [ @main, @main.facts.build ], local: true) do |form| %>

<div><%= form.text_field :tip,  :placeholder => "ENTER NEW FACTS HERE", :class => "pdtnametxt" %>
</div>

<div><%= form.submit :CREATE, :class => "createbtn" %></div>
<% end %>

app/views/mains/_signedhome.html.erb
<% if user_signed_in? %>
<% if current_user.email=="justfish@gmail.com" %>

<!-- JUST FISH LOGO -->

<div class="wrap intro">
	<div class="slideshow-container">
    <%= button_to "LOGOUT", destroy_user_session_path, method: :delete, :class => "createbtn", :style => "width: 10%; font-size: 1.5vw; position: absolute; right: 0.25vw; top: 0.25vw; border: 0.2vw solid black; background: white; color: red; text-shadow: none;" %>
    <%= button_to current_user.email, edit_user_registration_path, :method => "get", :class => "createbtn", :style => "width: 22%; font-size: 1.5vw; position: absolute; right: 10.25vw; top: 0.25vw; border: 0.2vw solid black; background: white; color: red; text-shadow: none;" %>
    <%= button_to "NEW BACKGROUND", new_main_background_path(@main), :method => "get", :class => "createbtn", :style => "width: 16%; font-size: 1.5vw; position: absolute; right: 0.25vw; bottom: 0.25vw; border: 0.2vw solid black; background: white; color: red; text-shadow: none;" %>
    <%= button_to "ALL BACKGROUNDS",main_backgrounds_path(@main), :method => "get", :class => "createbtn", :style => "width: 16%; font-size: 1.5vw; position: absolute; right: 16.25vw; bottom: 0.25vw; border: 0.2vw solid black; background: white; color: red; text-shadow: none;" %>
    <% if @main.backgrounds.blank? %>
      <img src="/assets/f1.png" style="width:100%; height: 45vw; border: 1px solid black; background: black" >
    <% else %>
      <% @main.backgrounds.shuffle.each do |background| %>
        <div class="logo fade0">
          <img src="/assets/f1.png" style="width:100%; height: 45vw; border: 1px solid black; background-image: url('<%= background.backgroundimg.url %>');background-size: cover;background-position: center;background-repeat: no-repeat" >
        </div>
      <% end %>
    <% end %>
  </div>
</div>

<!-- IMAGE SLIDER -->

<div class="wrap imgshow">
  <div class="slideshow-container">
    <%= button_to "NEW IMAGE", new_main_gallery_path(@main), :method => "get", :class => "createbtn", :style => "width: 16%; font-size: 1.5vw; position: absolute; right: 0.25vw; bottom: 0.25vw; border: 0.2vw solid black; background: white; color: red; text-shadow: none;" %>
    <%= button_to "ALL IMAGES",main_galleries_path(@main), :method => "get", :class => "createbtn", :style => "width: 16%; font-size: 1.5vw; position: absolute; right: 16.25vw; bottom: 0.25vw; border: 0.2vw solid black; background: white; color: red; text-shadow: none;" %>
    <% if @main.galleries.blank? %>
      <div class="mySlides fade">
        <img src="/assets/j1.jpg" style="object-fit: cover; width:100%; height: 55vw; border: 1px solid black" >
      </div>
    <% else %>
      <% @main.galleries.each do |gallery| %>
        <div class="mySlides fade">
          <%= image_tag gallery.galleryimg.url, :style => "object-fit: cover; width:100%; height: 55vw; border: 1px solid black" %>
        </div>
      <% end %>
    <% end %>

<!-- Side buttons to change image -->

    <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
    <a class="next" onclick="plusSlides(1)">&#10095;</a>

  </div>
</div>


<!-- FACTS, ABOUT US, NEW ARRIVALS -->


<div class="wrap mid">

<!-- DOTS FOR IMAGE GALLERY SLIDER -->

  <span class="dot" onclick="currentSlide(1)"></span> 
  <span class="dot" onclick="currentSlide(2)"></span> 
  <span class="dot" onclick="currentSlide(3)"></span> 
  <br>
  <br>

<!-- HEADINGS: FACTS, ABOUT and NEW ARRIVALS -->

  <table class="main">
    <tr>
      <th>
        DID YOU KNOW?
      </th>
      <th>
        ABOUT US
      </th>
      <th>
        NEW ARRIVALS
      </th>
    </tr>
  </table>

  <!-- INNER TABLES CONTAING DATA -->

  <table class="main">
    <tr>
      <td>

        <!-- DID YOU KNOW COLUMN -->

        <table class="inner">
          <tr>
            <th>
              <%@main.facts.each do |fact| %> 
                <div class="slideshow-container">
                  <div class="diduknow fade">
                    <span class="factsandarrivals">
                      <%= fact.tip %>
                    </span>
                    <span class="factsandarrivals"><%= button_to 'Delete', [fact.main, fact], method: :delete, data: { confirm: 'Are you sure?' }, :class => "dltbtn" %>
                    </span>
                    <span><a class="prev1" onclick="plusfacts(-1)">&#10094;</a>
                          <a class="next1" onclick="plusfacts(1)">&#10095;</a>
                    </span>
                  </div>
                </div>
              <% end %>
            </th>
          </tr>
        </table>
      </td>
      <td>

        <!-- ABOUT US COLUMN -->

        <table class="inner">
          
            <% i=0 %>
            <% @main.abouts.each do %>
              <% i=i+1 %>
            <% end %>

            <% if i==0 %>
              <%= render 'abouts/form' %>
            <% else %>
              <% @main.abouts.each do |about| %>
                <tr>
                  <th>     
                    <div class="about">
                      <%= about.data %>
                    </div>
                      <%= button_to 'Delete', [about.main, about], 
                          method: :delete, data: { confirm: 'Are you sure?' }, :class => "dltbtn" %>  
                  </th>
                </tr>
              <% end %>
            <% end %>
          
        </table>
      </td>
      <td>

        <!-- NEW ARRIVALS COLUMN -->
        <table class="inner">
          <div class="slideshow-container">
            <% @main.newarrivals.each do |newarrival| %>
              <%= link_to main_newarrival_path(@main, newarrival) do %>
                <div class="newarrival fade">
                  <span class="factsandarrivals" style="width: 83%; padding: 0.3vw; border: 0.12vw solid black; border-radius: 0.5vw">
                    <%= image_tag(newarrival.newarrivalimg.url, :class => "productimg3") %>
                  </span>  
                  <span>
                  <button class="factsandarrivalsheading">
                    <%= newarrival.name %>
                  </button>
                  <%= button_to 'Delete', [newarrival.main, newarrival], 
                          method: :delete, data: { confirm: 'Are you sure?' }, :class => "dltbtn", :style => "margin-top: 0.5vw;" %>
                </div>
                <br>
                <br>
                <%= button_to "ALL NEW ARRIVALS", main_newarrivals_path(@main), :method => "get", :class => "createbtn", :style => "width: 50%; font-size: 1.5vw; position: absolute; right: 0.25vw; bottom: 0.25vw; border: 0.2vw solid black; background: white; color: red; text-shadow: none;" %>
              <% end %>
              <span>
                <a class="prev1" onclick="plusarrival(-1)" style="text-shadow: none; font-size: 1.2vw">&#10094;</a>
                <a class="next1" onclick="plusarrival(1)" style="text-shadow: none; font-size: 1.2vw">&#10095;</a>
              </span>
            <% end %>
          </div>
        </table>
      </td>
    </tr>
  </table>

  <!-- THIRD COLUMN: TO ADD NEW FACTS/NEW ARRIVALS -->
  <table class="main">
    <tr>
      <td>
        <%= render 'facts/form' %>
      </td>
      <td>
      </td>
      <td>
        <%= render 'newarrivals/form' %>
      </td>
    </tr>
  </table>
  <br> 
</div>

<!-- PRODUCTS SLIDER -->

<div class="wrap prod">
  <br>
  <table class="categories">
    <tr>
      <th>
        <div class="ourpdt">OUR PRODUCTS</div>
      </th>
    </tr>
  </table>
  <br>
  <div class="category2" style="margin-bottom: 4vw; position: relative;">
        <% @categories = Category.all %>
        <div class="categorylogin">
          <% @categories.each do |category| %>
            <% if category.catimg? %>
            <div class="a123" style="background-image: url('<%= category.catimg.url %>');background-size: cover;background-repeat: no-repeat">
            <% else %>
            <div class="a123">
            <% end %>
              <%= button_to category.catname, category_path(category), :method => "get", :class => "btncls" %>
            </div>
          <% end %>
        </div>
  </div>
  <%= button_to "CREATE NEW CATEGORY", new_category_path, :method => "get", :class => "createbtn", :style => "width: 19%; font-size: 1.5vw; position: absolute; right: 16.25vw; bottom: 0.25vw; border: 0.2vw solid black; background: white; color: red; text-shadow: none;" %> 
        <%= button_to "ALL PRODUCTS", products_path, :method => "get", :class => "createbtn", :style => "width: 16%; font-size: 1.5vw; position: absolute; right: 0.25vw; bottom: 0.25vw; border: 0.2vw solid black; background: white; color: red; text-shadow: none;" %>
</div>

<!-- BOTTOM SET - CONTACTS, LOCATION, CAREERS -->

  <div class="wrap bottom" style="position: relative; min-height: 36vw">
  <br>
  <table class="bottomtable">
    <tr>
      <th>
          <div class="heading">CONTACT US</div>
      </th>
      <th>
        <div class="heading">LOCATE US</div>
      </th>
      <th>
        <div class="heading">CAREERS</div>
      </th>
    </tr>
    <tr>
      <td>

        <!-- CONTACT DETAILS -->

        <div class="btmcontents1">
          <%= @main.shop %>
        </div>
        <br>
          <div class="btmcontents">
            <%= image_tag("contactmail.png", class: :contactset) %>
            <%= @main.contact_mail %>
        </div>
        <br>
        <div class="btmcontents">
          <%= image_tag("phone.png", class: :contactset) %>
          <%= @main.contact_no %>
          </div>
        <br>
        <div class="btmcontents">
          <%= image_tag("mapsymbol.png", class: :contactset) %>
          <%= simple_format @main.address %>
        </div>
        <%= button_to "EDIT CONTACT INFO", edit_main_path(@main), :method => "get", :class => "createbtn", :style => "width: 17%; font-size: 1.5vw; position: absolute; left: 7.7vw; bottom: 3.25vw; border: 0.2vw solid black; background: white; color: red; text-shadow: none" %>
      </td>

      <!-- MAP -->

      <td>
        <div class="btmcontents"><%= link_to image_tag("map.jpg", class: :location), "https://www.google.co.in/maps/place/Just+Fish/@10.0695466,76.3308314,20.19z/data=!4m5!3m4!1s0x3b080e81fbeafe9b:0x10ba505a574cde92!8m2!3d10.0694962!4d76.3308634", target: :_blank %>
        </div>
      </td>

      <!-- CAREER LIST -->

      <td>
        <div class="container">
        <% @careers = Career.all %>
        <% i=0 %>
        <% @careers.each do |career| %>

          <!-- OPENING THE DIV BOX TO START SHOWING THREE ELEMENTS EACH -->

          <% if i%3==0 %>
            <div class="career1">
          <% end %>
          <% i=i+1 %>
          <%= button_to career.career_name, career_path(career), :method => "get", :class => "careerbtn" %>
          
          <!-- PROVIDING LINE BREAKS TO SEPARATE CAREER NAMES -->

          <% if i%3!=0 %>
            <br>
          <% end %>

          <!-- CLOSING THE DIV BOX WHEN THREE ELEMENTS ARE FILLED -->

          <% if i%3==0 %>
            </div>
          <% end %>

          <!-- BUTTONS TO SLIDE THE CAREER LIST -->

          <a class="prev2" onclick="pluscareer(-1)">&#10094;</a>
          <a class="next2" onclick="pluscareer(1)">&#10095;</a>
        <% end %>

      <!-- PROVIDING LINK TO CREATE NEW CAREER INFO -->
      
      </div>
      <br>
    </td>
    </tr>
   </table>
  <% career = Career.new %>
  <%= button_to "CREATE CAREER INFO", new_career_path, :method => "get", :class => "createbtn", :style => "width: 17%; font-size: 1.5vw; position: absolute; right: 15.25vw; bottom: 3.25vw; border: 0.2vw solid black; background: white; color: red; text-shadow: none;" %> 
  <%= button_to "ALL CAREERS", careers_path, :method => "get", :class => "createbtn", :style => "width: 15%; font-size: 1.5vw; position: absolute; right: 0.25vw; bottom: 3.25vw; border: 0.2vw solid black; background: white; color: red; text-shadow: none;" %>
  </div>
<% end %>
<% end %>

app/views/mains/edit.html.erb
<%= form_with(model: @main, local: true) do |form| %>
<fieldset class="catwrap">
	<legend class="legend">EDIT CONTACT INFO</legend>
<br>
<div><%= form.text_field :shop,  :placeholder => "ENTER CONTACT NAME HERE", :class => "pdtnametxt" %>
</div>
<br>
<div><%= form.text_field :contact_mail,  :placeholder => "ENTER CONTACT EMAIL ID HERE", :class => "pdtnametxt" %>
</div>
<br>
<div><%= form.text_field :contact_no,  :placeholder => "ENTER CONTACT NUMBER HERE", :class => "pdtnametxt" %>
</div>
<br>
<div><%= form.text_area :address,  :placeholder => "ENTER CONTACT ADDRESS HERE", :class => "addressfield" %>
</div>
<div class="productback">
	<%= form.submit :SAVE, :class => "createbtn" %>
</div>
<div class="productback">
		<%= button_to 'Back to Main page', root_path, :method => "get", :class => "createbtn" %>
</div>
<% end %>
</fieldset>

app/views/mains/show.html.erb
<% if user_signed_in? %>
<% if current_user.email=="justfish@gmail.com" %>
<%= render 'signedhome' %>
<% end %>

<% else %>
<!-- JUST FISH LOGO -->

<div class="wrap intro">
	<div class="slideshow-container">
    <% if @main.backgrounds.blank? %>
      <img src="/assets/f1.png" style="width:100%; height: 45vw; border: 1px solid black; background: black" >
    <% else %>
      <% @main.backgrounds.shuffle.each do |background| %>
        <div class="logo fade0">
          <img src="/assets/f1.png" style="width:100%; height: 45vw; border: 1px solid black; background-image: url('<%= background.backgroundimg.url %>');background-size: cover;background-position: center;background-repeat: no-repeat" >
        </div>
      <% end %>
    <% end %>
  </div>
</div>


<!-- IMAGE SLIDER -->

<div class="wrap imgshow">
  <div class="slideshow-container">
    <% if @main.galleries.blank? %>
      <div class="mySlides fade">
        <img src="/assets/j1.jpg" style="object-fit: cover; width:100%; height: 55vw; border: 1px solid black" >
      </div>
    <% else %>
    <% @main.galleries.each do |gallery| %>
    <div class="mySlides fade">
        <%= image_tag gallery.galleryimg.url, :style => "object-fit: cover; width:100%; height: 55vw; border: 1px solid black" %>
    </div>
    <% end %>
    <% end %>

<!-- Side buttons to change image -->

    <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
    <a class="next" onclick="plusSlides(1)">&#10095;</a>

  </div>
</div>


<!-- FACTS, ABOUT US, NEW ARRIVALS -->


<div class="wrap mid">

<!-- DOTS FOR IMAGE GALLERY SLIDER -->

  <span class="dot" onclick="currentSlide(1)"></span> 
  <span class="dot" onclick="currentSlide(2)"></span> 
  <span class="dot" onclick="currentSlide(3)"></span> 
  <br>
  <br>

<!-- HEADINGS: FACTS, ABOUT and NEW ARRIVALS -->

  <table class="main">
    <tr>
      <th>
        DID YOU KNOW?
      </th>
      <th>
        ABOUT US
      </th>
      <th>
        NEW ARRIVALS
      </th>
    </tr>
  </table>

  <!-- INNER TABLES CONTAING DATA -->

  <table class="main">
    <tr>
      <td>

        <!-- DID YOU KNOW COLUMN -->

        <table class="inner">
          <tr>
            <th>
              <%@main.facts.each do |fact| %> 
                <div class="slideshow-container">
                  <div class="diduknow fade1">
                    <span class="factsandarrivals">
                      <%= fact.tip %>
                    </span>
                    <span><a class="prev1" onclick="plusfacts(-1)">&#10094;</a>
                          <a class="next1" onclick="plusfacts(1)">&#10095;</a>
                    </span>
                  </div>
                </div>
              <% end %>
            </th>
          </tr>
        </table>
      </td>
      <td>

        <!-- ABOUT US COLUMN -->

        <table class="inner">
          
            <% i=0 %>
            <% @main.abouts.each do %>
              <% i=i+1 %>
            <% end %>

            <% if i==0 %>
              <%= render 'abouts/form' %>
            <% else %>
              <% @main.abouts.each do |about| %>
                <tr>
                  <th>
                    <div class="about">
                      <%= about.data %>
                    </div>
                  </th>
                </tr>
              <% end %>
            <% end %>
          
        </table>
      </td>
      <td>

        <!-- NEW ARRIVALS COLUMN -->

        <table class="inner">
          <div class="slideshow-container">
            <% @main.newarrivals.each do |newarrival| %>
              <%= link_to main_newarrival_path(@main, newarrival) do %>
                <div class="newarrival fade1">
                  <span class="factsandarrivals" style="width: 83%; padding: 0.3vw; border: 0.12vw solid black; border-radius: 0.5vw">
                    <%= image_tag(newarrival.newarrivalimg.url, :class => "productimg3") %>
                  </span>  
                  <span>
                  <button class="factsandarrivalsheading">
                    <%= newarrival.name %>
                  </button>
                </div>
              <% end %>
              <span>
                <a class="prev1" onclick="plusarrival(-1)" style="text-shadow: none; font-size: 1.2vw">&#10094;</a>
                <a class="next1" onclick="plusarrival(1)" style="text-shadow: none; font-size: 1.2vw">&#10095;</a>
              </span>
            <% end %>
          </div>
        </table>
      </td>
    </tr>
  </table>
  <br>
  <br>
</div>

<!-- PRODUCTS SLIDER -->

<div class="wrap prod">
  <br>
  <table class="categories">
    <tr>
      <th>
        <div class="ourpdt">OUR PRODUCTS</div>
      </th>
    </tr>
  </table>
  <br>
  <div class="category2">
        <% @categories = Category.all %>
        <% i=0 %>
        <% j=0 %>
        <% @categories.each do |category| %>
          <% if i%4==0 %>
          <% j=j+1 %>
          <div class="category">
          <% end %>
            <% i=i+1 %>
            <span class="a123" style="background-image: url('<%= category.catimg.url %>');background-size: cover;background-repeat: no-repeat; background-position: center; box-shadow: 0.3vw 0.3vw black, 0.3vw 0.3vw 0.4vw red; margin: 0.15vw">
              <%= button_to category.catname, category_path(category), :method => "get", :class => "btncls" %></button>
            </span>
          <% if i%4==0 %>
            <% i=0 %>
            </div>
          <% end %> 
          <a class="prev3" onclick="pluscategory(-1)">&#10094;</a>
          <a class="next3" onclick="pluscategory(1)">&#10095;</a>
        <% end %>
        <% if i%4!=0 %>
      </div>
      <% end %>
  </div>
  <% (1..j).each do |i| %>
  <span class="dot1" onclick="currentcategory(<%= i %>)"></span>
  <% end %> 
  <br>
  <br>
  <%= button_to 'All Products', products_path, :method => "get", :class => "createbtn", :style => "width: 12%; font-size: 1.3vw; position: absolute; right: 0; bottom: 0; border: none" %>
</div>


<!-- BOTTOM SET - CONTACTS, LOCATION, CAREERS -->

  <div class="wrap bottom" style="position: relative; min-height: 33vw">
  <br>
  <table class="bottomtable">
    <tr>
      <th>
          <div class="heading">CONTACT US</div>
      </th>
      <th>
        <div class="heading">LOCATE US</div>
      </th>
      <th>
        <div class="heading">CAREERS</div>
      </th>
    </tr>
    <tr>
      <td>

        <!-- CONTACT DETAILS -->

        <div class="btmcontents1">
          <%= @main.shop %>
        </div>
        <br>
          <div class="btmcontents">
            <%= image_tag("contactmail.png", class: :contactset) %>
            <%= @main.contact_mail %>
        </div>
        <br>
        <div class="btmcontents">
          <%= image_tag("phone.png", class: :contactset) %>
          <%= @main.contact_no %>
          </div>
        <br>
        <div class="btmcontents">
          <%= image_tag("mapsymbol.png", class: :contactset) %>
          <%= simple_format @main.address %>
        </div>
      </td>

      <!-- MAP -->

      <td>
        <div class="btmcontents"><%= link_to image_tag("map.jpg", class: :location), "https://www.google.co.in/maps/place/Just+Fish/@10.0695466,76.3308314,20.19z/data=!4m5!3m4!1s0x3b080e81fbeafe9b:0x10ba505a574cde92!8m2!3d10.0694962!4d76.3308634", target: :_blank %>
        </div>
      </td>

      <!-- CAREER LIST -->

      <td>
        <div class="container">
        <% @careers = Career.all %>
        <% i=0 %>
        <% @careers.each do |career| %>

          <!-- OPENING THE DIV BOX TO START SHOWING THREE ELEMENTS EACH -->

          <% if i%3==0 %>
            <div class="career1">
          <% end %>
          <% i=i+1 %>
          <%= button_to career.career_name, career_path(career), :method => "get", :class => "careerbtn" %>
          
          <!-- PROVIDING LINE BREAKS TO SEPARATE CAREER NAMES -->

          <% if i%3!=0 %>
            <br>
          <% end %>

          <!-- CLOSING THE DIV BOX WHEN THREE ELEMENTS ARE FILLED -->

          <% if i%3==0 %>
            </div>
          <% end %>

          <!-- BUTTONS TO SLIDE THE CAREER LIST -->

          <a class="prev2" onclick="pluscareer(-1)">&#10094;</a>
          <a class="next2" onclick="pluscareer(1)">&#10095;</a>
        <% end %>
        
        </div>  
        <br>
      </td>
    </tr>
  </table>
  <%= button_to 'All CAREERS', careers_path, :method => "get", :class => "createbtn", :style => "width: 12%; font-size: 1.3vw; position: absolute; right: 0; bottom: 0.25vw; border: none" %>
</div>
<div class="wrap bottom" style="min-height: 7vw; padding: 1vw; position: relative;background-position: center">
  <div style="text-align: left; font-family: 'Fresca'; width: 33%; margin: 0 auto; float: left"><b style="font-size: 2vw; text-shadow: 0 0 0.02vw blue">CREDITS:</b><br> HNYJNY & ABNVKS</div>
  <div style="font-family: 'Fresca'; width: 33%; display: inline-block; margin: 0 auto; float: left"><b style="font-size: 2vw; text-shadow: 0 0 0.02vw blue">OUR PARTNERS:</b><br> COCHIN AQUARIUM</div>
  <%= link_to new_user_session_path do |f| %>
  <div class="btmlogin">LOG IN</div>
</div>
  <% end %>
<% end %>