config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'mains/show'
  resources :mains do resources :facts
                      resources :newarrivals
                      resources :abouts
                      resources :backgrounds
                      resources :galleries
  end

  resources :categories do resources :products
  end

  resources :careers
  resources :products

  root 'mains#show'
  
end

app/models/about.rb
class About < ApplicationRecord
  belongs_to :main


main = Main.find_by(id: '1')
i=0
main.abouts.each do
i=i+1
end
if i==0
about = main.abouts.create(sl: "1", data: "THE COMPLETE AQUATIC SOLUTIONS")
about.save
end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/background.rb
class Background < ApplicationRecord
  belongs_to :main
  mount_uploader :backgroundimg, BackgroundimgUploader
end

app/models/career.rb
class Career < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products, dependent: :destroy
  mount_uploader :catimg, CatimgUploader
end

app/models/fact.rb
class Fact < ApplicationRecord
  belongs_to :main
end

app/models/gallery.rb
class Gallery < ApplicationRecord
  belongs_to :main
  mount_uploader :galleryimg, GalleryimgUploader
end

app/models/main.rb
class Main < ApplicationRecord
has_many :facts, dependent: :destroy
has_many :abouts, dependent: :destroy
has_many :newarrivals, dependent: :destroy
has_many :backgrounds, dependent: :destroy
has_many :galleries, dependent: :destroy

mains = Main.all
i=0
mains.each do |check|
i=i+1
end
if i==0
main = Main.create(id: "1")
main.save
end
end

app/models/newarrival.rb
class Newarrival < ApplicationRecord
  belongs_to :main
  mount_uploader :newarrivalimg, NewarrivalimgUploader
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  mount_uploader :pdtimg, PdtimgUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
before_action :authenticate_user!, except: [:show, :index]

def index
	@categories = Category.all
end

 def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
  end

  def edit
    @category = Category.find(params[:id])
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to @category
    else
      render 'new'
    end
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      redirect_to @category
    else
      render 'edit'
    end
  end
  
  def destroy
    @category = Category.find(params[:id])
    @category.destroy
 
    redirect_to root_path
  end

  private
    def category_params
      params.require(:category).permit(:catname, :catimg, :catimg)
    end

end

app/controllers/facts_controller.rb
class FactsController < ApplicationController
before_action :authenticate_user!
def create
  @main = Main.find_by(id: '1')
  @fact = @main.facts.create(fact_params)
  redirect_to main_path(@main)
end

def destroy
  @main = Main.find_by(id: '1')
  @fact = @main.facts.find(params[:id])
  @fact.destroy
  redirect_to main_path(@main)
end

private
  def fact_params
    params.require(:fact).permit(:tip)
  end


end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/backgrounds_helper.rb
module BackgroundsHelper
end

app/helpers/careers_helper.rb
module CareersHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/facts_helper.rb
module FactsHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/mains_helper.rb
module MainsHelper
end

app/helpers/newarrivals_helper.rb
module NewarrivalsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/categories/_form.html.erb
<fieldset class="catwrap">
	<legend class="legend">NEW CATEGORY</legend>
	<div class="newprod">
		<%= form_with(model: @category, local: true) do |form| %>
			<div>
				<%= form.text_field :catname,  :placeholder => "ENTER NEW CATEGORY HERE", :class => "pdtnametxt" %>
			</div>
			<br>
			<div>
				<%= form.file_field :catimg, :class => "pdtnametxt" %>
			</div>
			<br>
			<div class="productback">
				<%= form.submit :SAVE, :class => "createbtn" %>
			</div>
		<% end %>
		<div class="productback">
			<%= button_to 'Back to Main page', root_path, :method => "get", :class => "createbtn" %>
		</div>
	</div>
</fieldset>

app/views/categories/edit.html.erb
<%= render 'form' %>

app/views/categories/index.html.erb
<div class="catwrap" style="position: relative">
<fieldset>
	<legend class="prodlegend" style="font-size: 4vw; margin-left: 2vw">ALL CATEGORIES</legend>
		<% @categories.shuffle.each do |category| %>
				<%= link_to category_path(category) do %>
				<div class="categoryindex">
					<div style="padding-bottom: 0.5vw; min-height: 13.1vw"><%= image_tag(category.catimg.url, class: :productimg1) %></div>
  				<button class="pdtnamebtn"><%= category.catname %></button>
          <% if user_signed_in? and current_user.email =="justfish@gmail.com" %>
            <%= link_to 'Delete', category_path(category), method: :delete, data: { confirm: 'Are you sure?' }, :class => "dltbtn" %>
          <% end %>
  			</div>
  			<% end %>
		<% end %>
</fieldset>
<div style="padding: 0.3vw">
			<%= button_to 'Back to Main page', root_path, :method => "get", :class => "createbtn" %>
		</div>
	<%= button_to 'HOME', root_path, :method => "get", :class => "homebtn" %>
    <%= button_to 'PRODUCTS', products_path, :method => "get", :class => "catbtn" %>
</div>

app/views/categories/show.html.erb
<div class="catwrap" style="position: relative">
	<fieldset style="margin-top: 2vw">
		<legend class="legend">
  			LIST OF <%= @category.catname %>
  		</legend>
		<% @category.products.each do |product| %>
			<%= link_to category_product_path(@category, product) do %>
				<div class="categoryproducts">
  					<div style="padding-bottom: 0.5vw; min-height: 13.1vw"><%= image_tag(product.pdtimg.url, class: :productimg1) %></div>
    				<button style="width: 100%" class="pdtnamebtn"><%= product.pdtname %></button>
    				<% if user_signed_in? and current_user.email =="justfish@gmail.com" %>
						<%= link_to 'Delete', [product.category, product], method: :delete, data: { confirm: 'Are you sure?' }, :class => "dltbtn" %>
               		<% end %>
    			</div>
    		<% end %>	
		<% end %>
	</fieldset>

	<div class="productback">
		<%= button_to 'Back to Main page', root_path, :method => "get", :class => "createbtn" %>
	</div>
	<% if user_signed_in? %>
	<% if current_user.email =="justfish@gmail.com" %>
	<div class="productback">
		<%= button_to 'Edit Category', edit_category_path(@category), :method => "get", :class => "createbtn" %>
	</div>
	<div class="categorydeleter">
		<%= button_to 'Delete Category', category_path(@category), method: :delete, data: { confirm: 'Are you sure?'}, :class => "createbtn" %>
	</div>

	<div class="productrender">
		<%= render 'products/form' %>	
	</div>
	<% end %>
	<% end %> 
	<%= button_to 'HOME', root_path, :method => "get", :class => "homebtn", :style => "right: 23vw" %>
    <%= button_to 'CATEGORIES', categories_path, :method => "get", :class => "catbtn", :style => "right: 0vw" %>
    <%= button_to 'PRODUCTS', products_path, :method => "get", :class => "catbtn", :style => "right: 12vw" %>
</div>